### ISSUE TITLE
밋업 장소 안내

### ISSUE THREAD

**Issue by riseshia** [riseshia/cal4w#1]
좌표로 지정 또는 핀박기 등등...?

**Comment by ujuc** [comment]
[openstreetmap](https://www.openstreetmap.org/) 쪽 API를 사용하면 될듯요.

**Comment by riseshia** [comment]
해주세요!

**Comment by Pluu** [comment]
[Google Places API](https://developers.google.com/places/?hl=ko) 이런것들도 있다죠

**Comment by riseshia** [comment]
@Pluu 구글지도도 미묘하지 않나요? 물론 오픈스트리트보다야 정확하겠지만!

**Comment by Pluu** [comment]
@riseshia 담당 개발자가 잘하시겠죠!

**Comment by riseshia** [comment]
ですよね。。。
아 콜라보레이터가 아니라 담당을 못주는구나! 큿....

**Comment by Pluu** [comment]
난 안드개발자 안드개발자

**Comment by riseshia** [comment]
이번기회에 웹도 한번 =3

**Comment by Pluu** [comment]
@riseshia HTML이 아니라 레일즈일것같은 기분이드네요

**Comment by riseshia** [comment]
Rails 아니고 노드로 하셔도 되고 스프링으로 하셔도 돼요 :+1:

**Comment by ujuc** [comment]
구글은 비쌈요.... 

오픈소스는 어떨지모르겠는데.ㅡ.ㅡ;;

**Comment by ujuc** [comment]
https://developers.google.com/maps/documentation/embed/?hl=ko

이건 무제한 무료인데..음..

**Comment by ujuc** [comment]
https://google-developers.appspot.com/maps/documentation/embed/start?hl=ko

요로코롬 씁시다. 붙여야겠네... 오늘 작업!

**Comment by ujuc** [comment]
@riseshia 테스팅 하셔야되요~~~ 테스팅..
