### ISSUE TITLE
이벤트 조인 후 에러메세지 뜸

### ISSUE THREAD

**Issue by minieetea** [riseshia/cal4w#101]
If you are the application owner check the logs for more information.

**Comment by ujuc** [comment]
![2016-05-19 18 50 35](https://cloud.githubusercontent.com/assets/624975/15389580/9aef409c-1df2-11e6-8f77-d6ac58a6e5bb.png)

스샷 첨부

**Comment by riseshia** [comment]
#105 관련 중복입니다.
이번에 구조를 바꾸면서 @ 없이 저장 -> 잘못된 DM요청.. 그리고 에러 핸들링이 잘 되지 않았다는 슬픈 기록이었습니다. ㅇ<-<
일단 고쳤는데 문제 없으면 닫아주시면 감사하겠습니다...

**Comment by ujuc** [comment]
어흨..ㅠ.ㅠ. @riseshia 고생하셨시유..
