### ISSUE TITLE
동일 아이디로 이벤트에 2명이 조인됨? 

### ISSUE THREAD

**Issue by minieetea** [riseshia/cal4w#102]
재현은 안되는 것 같습니당 헤헤 

![2016-05-19 4 20 17](https://cloud.githubusercontent.com/assets/4803062/15385672/11867b72-1dde-11e6-97b0-6d5d6b9bf007.png)

**Comment by riseshia** [comment]
#105 랑 비슷한원인으로 추정중입니다. 나중에 확인해보시고 재현 안되면 그냥 닫아주시면 됩니다!

**Comment by minieetea** [comment]
고생하셨어요
