### ISSUE TITLE
시간이 꼬이면 수정 권한이 사라짐

### ISSUE THREAD

**Issue by minieetea** [riseshia/cal4w#108]
**오늘 밤 10~ 오늘 새벽 1시** 로 지정하는 경우, EDIT이 되지 않음
(시작시간보다 종료시간이 이른경우)

**Comment by minieetea** [comment]
#104  와 관련

**Comment by ujuc** [comment]
이건 어떻게.. 다시 열린이유는 뭔가요???

**Comment by riseshia** [comment]
검증이 없어서요 'ㅅ'
