### ISSUE TITLE
오랜만에 local에서 개발하는데 auth 인증이 실패한 걸로 보입니다

### ISSUE THREAD

**Issue by say8425** [riseshia/cal4w#127]
<img width="1608" alt="2016-06-05 9 09 19" src="https://cloud.githubusercontent.com/assets/3258867/15805336/d1989b4e-2b61-11e6-977d-1b989237efe6.png">
서버 키고, sign in with slack을 진행하니 저렇게 뜹니다.
어떻게 해야 진행 할 수 있나요?
안 본 사이 너무 고도화 되어서 쫓아가지를 못했네요ㅠ

**Comment by riseshia** [comment]
해결했으니 닫습니다
