### ISSUE TITLE
제가 등록한 건데도.. 수정할 수 있는 방법이.ㅡ.ㅡ;;;

### ISSUE THREAD

**Issue by ujuc** [riseshia/cal4w#146]
모바일로 생성한 일정일 경우에는... 데스크탑에서는 수정할 수 없는 버그인가.ㅡ.ㅡ;;;

<img width="817" alt="2016-07-03 3 05 42" src="https://cloud.githubusercontent.com/assets/624975/16544017/c9bc7bd2-412f-11e6-9f97-25893ed97d51.png">

모바일로 접근해서 수정해야도리듯..ㅠ.ㅠ.

**Comment by riseshia** [comment]
그거 아닐까요. 이전에 인증 바꾸면서 구 인증 세션이 남아있음 => 보기엔 같은 사람인데 실제로는 다른 유저라든가....

**Comment by riseshia** [comment]
@ujuc 해당 문제가 아직 재현되는 것이 아니라면 닫죠 'ㅅ'/

**Comment by ujuc** [comment]
잘안쓰다보니.ㅡ.ㅡ;

**Comment by riseshia** [comment]
ㅋㅋ.....
