### ISSUE TITLE
밋업 등록안됨

### ISSUE THREAD

**Issue by Pluu** [riseshia/cal4w#197]
![default](https://cloud.githubusercontent.com/assets/1534926/18229533/d399d708-72b7-11e6-9eff-0336e9920a43.PNG)

밋업 등록할려구하는데, 시작시간 문제로 계속 등록이 안되네요

**Comment by Pluu** [comment]
![default](https://cloud.githubusercontent.com/assets/1534926/18229592/c20610ea-72b9-11e6-9eec-186aa039e105.PNG)

혹시나해서 입력할때 값 표시

**Comment by riseshia** [comment]
👍

**Comment by riseshia** [comment]
고쳐서 배포했습니다 'ㅅ'/
