### ISSUE TITLE
썸...썸머타임......

### ISSUE THREAD

**Issue by riseshia** [riseshia/cal4w#210]

**Comment by riseshia** [comment]
생각해보니 타임존을 받을 것이 아니라, 지역 정보를 가지고 있어야 함 'ㅅ'

**Comment by ujuc** [comment]
설마...!! 안된건가요!!1
이런..!!

**Comment by riseshia** [comment]
@ujuc 애초에 지역정보를 받은 적도 없어서... 이벤트 별로 타임존을 받을게 아니라, 지역정보를 받아야할듯 =ㅂ=;

**Comment by justinyoo** [comment]
슬랙에 계정별로 각자 타임존 정보 있는데 그거 갖고 올 수 없나효?

**Comment by riseshia** [comment]
....!? api에 들어있어요? 금시초문인데 제보 감사합니다. 그쪽도 한번 확인해볼게요!

**Comment by justinyoo** [comment]
@riseshia 어... 없나? ㅋ

**Comment by riseshia** [comment]
@justinyoo 찾아보고 알려드리겠습니다. 결과는 일주일쯤 뒤에...!

**Comment by riseshia** [comment]
@justinyoo 새로 배포해서 동작확인했습니다. 확인 부탁드립니다 > <
