### ISSUE TITLE
슬랙 봇 프로필 사진 바꾸기

### ISSUE THREAD

**Issue by riseshia** [riseshia/cal4w#26]

**Comment by ujuc** [comment]
어떤 아이콘을 바꿀껀가요?

아이콘으로 사용 할 만한게...

[Font Awesome](https://fortawesome.github.io/Font-Awesome/)
이게 항상 업뎃되고 변경하기도 쉬워서 괜찮아요

**Comment by riseshia** [comment]
아, 제가 말한 아이콘은 슬랙 봇의 프로필 사진이었다고 합니다 ㅠㅠ...

**Comment by riseshia** [comment]
생각해보니 파비콘도 필요하겠네요. 별도 이슈로 만들겠습니다.

**Comment by ujuc** [comment]
아.ㅡ.ㅡ.. 아이콘 이라고 적어놔서.ㅡ.ㅡㅋㅋㅋ

**Comment by riseshia** [comment]
DONE!
