### ISSUE TITLE
Bootstrap 4.0.0 설치하여 사용

### ISSUE THREAD

**Issue by ujuc** [riseshia/cal4w#30]
[Gem bootstrap](https://rubygems.org/gems/bootstrap)

**Comment by riseshia** [comment]
왜 ㅋㅋㅋㅋ 왜 ㅋㅋㅋㅋ 4.0 ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by ujuc** [comment]
@riseshia 음... 왠지 UI 신경쓸때쯤.. 4.0이 나올것같아서요. ㅋㅋㅋㅋㅋㅋㅋ

**Comment by ujuc** [comment]
우선 안이쁘니.. 3.3.6 을 연결해서...... CDN으로 :)

**Comment by ujuc** [comment]
우리 이건 4.0나오면 합시다..

**Comment by say8425** [comment]
4.0.0아 제발 빨리 나와라

**Comment by riseshia** [comment]
그럼 닫읍시다!
