### ISSUE TITLE
좋은 파비콘 선택 & 적용하기

### ISSUE THREAD

**Issue by riseshia** [riseshia/cal4w#31]
역시 가장 좋아보이는건 이모 블로그에서 쓰고 있는 파비콘인것 같은데, 어떻게 생각하시나요?

**Comment by ujuc** [comment]
파비콘은 그냥 가져오면 될듯.. 알라님께 말씀드리고 받으면 되지않나요...?

내블로그도 파비콘이없는데.ㅡ.ㅡ;;; 남꺼 신경쓰는 1인..

**Comment by riseshia** [comment]
네. 이 부분은 여쭤보고 허락 받으면 그냥 그대로 가져다 쓰면 될거 같습니다 :+1:

**Comment by ujuc** [comment]
ㅇㅇㅇㅇㅇ ㅋㅋㅋㅋ 폰트 어썹을 이용하여 이것저것 잼있는것이 생각났...ㅋㅋㅋ 수정해야지.ㅡ.ㅡ

**Comment by riseshia** [comment]
허가 받았습니다. 붙이자!
