### ISSUE TITLE
정기 밋업에 대한 지원

### ISSUE THREAD

**Issue by riseshia** [riseshia/cal4w#35]
태그같은걸 사용해서 표시할 수 있도록 하고, 나중에 특정 태그 대상으로 노티를 받을 수 있는 시스템을 구성해서, 사이트에 직접 접속하지 않아도 알 수 있도록 'ㅂ'

**Comment by riseshia** [comment]
태그 말고 그냥 아예 프리셋. 시간 지정 + 제목 + 장소 + 설명을 재활용할 수 있게....?

**Comment by say8425** [comment]
ㅇㅇ 프리셋이 낫겠어요
근데 요걸 어떻게 설계해야할지는 감이 안잡히네요ㅠ

**Comment by riseshia** [comment]
본인이 이전에 만들었던 이력에서 끌어오면 간단!
복사해서 새로 만들기, 이런 기능 넣으면 될거 같아요 'ㅂ'
