### ISSUE TITLE
date picker 적용 어떠세요?

### ISSUE THREAD

**Issue by say8425** [riseshia/cal4w#38]
일정 추가 페이지의 날짜 항목에 [bootstrap daterange pickker](https://github.com/dangrossman/bootstrap-daterangepicker) 적용할까 하는데 어떠세요?
date picker는 별별거 다 써봤는데 얘가 제일 났더라요

**Comment by say8425** [comment]
생각해보니 몇날몇일이고 해커톤 할것도 아닌데, daterange picker는 오버였군요 ㅋㅋㅋ 방향 어떻게 잡아야할지 알겠어요 이제

**Comment by ujuc** [comment]
그거 넣었다가 덮였습니다.

**Comment by ujuc** [comment]
https://github.com/riseshia/cal4w/issues/32#issuecomment-194145146

여기서 나온걸로 한번해보고 아니다싶으면 다시 도전!

**Comment by riseshia** [comment]
알라님이 넣은걸로 충분한거 같은데 어떻게 보십니까.
문제 없다고 보시면 닫아주세요 :) @say8425

**Comment by say8425** [comment]
Absolutely amazing!!
클로즈 못박겠습니다🐧
