### ISSUE TITLE
혹시 '@' 일부러 포함 해서 입력하게 했나요?

### ISSUE THREAD

**Issue by say8425** [riseshia/cal4w#42]
처음 로그인할때 슬랙 아이디에 '@' 붙이잖아요
영어만 입력해도 클라단이나 서버단에서 '@'을 붙여서 slack에 쏴도
괜찮을 거 같은데 혹시 뭔가 이슈가 있었나요?

**Comment by riseshia** [comment]
의도한게 맞읍니다. 슬랙 호출할때에는 @를 붙여서 하니까, 이쪽이 친숙할까 싶어서 그렇게 적었어요. 'ㅂ'
어차피 얘는 이모Auth될 때까지 시한부 인생이니까... 대충대충... ㅇ<-<

**Comment by say8425** [comment]
과연,, 샤왕자 정도면 이 정도는 껌일텐데, 일부러 그렇게 짰나? 여겼어요 ㅋㅋㅋ
그러면 이거는 text field에 placeHolder로 '@weirdmeetup' 넣는 정도로
마무리 짓고싶은데 어떠세요?

**Comment by riseshia** [comment]
넹 해주세요 'ㅅ'/

**Comment by say8425** [comment]
하는김에 bootstrap validation check도 넣을게요~

**Comment by riseshia** [comment]
그러시죠 'ㅅ'/

**Comment by say8425** [comment]
이 이슈는 이제 닫죠~
