### ISSUE TITLE
사용자 연락처 등록 기능이 필요한가?

### ISSUE THREAD

**Issue by riseshia** [riseshia/cal4w#5]
1. 슬랙 계정명으로 충분하지 않을까?
2. 불충분하다면 받아야하는데 일회용? 아니면 데이터에 저장?
3. 개인정보 보관문제로 이슈가 될만한 여지는 없나?

**Comment by riseshia** [comment]
아예 매번 일회성으로 받고 파기하는 것도 괜찮을듯.

**Comment by ujuc** [comment]
음... 그렇게하면 항상 모임 시간이 없어지면 생성되는 것으로 보이는데... 음...

**Comment by riseshia** [comment]
모임시간이 없어지면 생성된다는게 무슨 의미인가요?

**Comment by ujuc** [comment]
이벤트 인듯합니다. 적어놓은걸 모르겠.ㅡ.ㅡ;

**Comment by riseshia** [comment]
일단 버리는 것으로 결정. 필요하면 누군가 다시 열어줄 것입니다...
