### ISSUE TITLE
Timezone 지원

### ISSUE THREAD

**Issue by haruair** [riseshia/cal4w#54]
이벤트 등록 시 타임존 지원.

@riseshia 님이 슬랙에서 언급하셨는데 기록 삼아 여기에도 둡니다.

**Comment by riseshia** [comment]
코드 좀 고치고 진행하죠. 서버쪽에서 사용자의 타임존 탐지하는건 별로고, js로 찾아서 올려주는것도 보기 싫으니, 서버는 UTC만 알고 브라우저에서 처리해주는 쪽으로 'ㅂ'!

**Comment by haruair** [comment]
넵, 좋습니다 :+1: moment-tz 같은 걸로 가나요?

2016-03-24 0:43 GMT+11:00 Shia notifications@github.com:

> 코드 좀 고치고 진행하죠. 서버쪽에서 사용자의 타임존 탐지하는건 별로고, js로 찾아서 올려주는것도 보기 싫으니, 서버는 UTC만
> 알고 브라우저에서 처리해주는 쪽으로 'ㅂ'!
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/riseshia/cal4w/issues/54#issuecomment-200349068

## 

Kind regards,

Edward Kim.

**Comment by riseshia** [comment]
지금도 캘린더 쪽 데이터는 moment만 써서 로컬 타임으로 변환하고 있어요.
UTC -> 브라우저 로컬로 변환하는건 TZ 플러그인 없어도 잘 되더라구요. 이건 브라우저에서 타임존 offset을 가져올수 있어서가 아닐까 추측하고 있긴한데, 코드를 까본건 아니라서 확실하진 않아요. 'ㅂ'!

이벤트 생성시에 타임존 정보 받고 -> UTC 변환 후 저장
클라이언트에 넘겨줄때 UTC -> 브라우저 타임존으로 변환(moment, 실질적으로는 full calendar가 해줌)

요런 느낌이 좋을까 하고 'ㅂ'

**Comment by haruair** [comment]
@riseshia 님 말씀처럼 전부 UTC로 저장하고 표현부에 대해서만 브라우저 기준의 타임존으로 보여주면 깔끔할 것 같아요. 백엔드에서 연산하면 tz도 받아야하고 복잡해질 수 있으니 프론트에서 아예 UTC로 연산해서 넘겨주는 것도 방법이 될 것 같아요.

구글 캘린더에도 timezone 설정이 있길래 참고 삼아서 화면 첨부했습니다.

![screen shot 2016-03-24 at 9 06 19 am](https://cloud.githubusercontent.com/assets/1009457/14002453/3e24f588-f1a0-11e5-85ac-9e98929fe96e.png)
![screen shot 2016-03-24 at 9 06 24 am](https://cloud.githubusercontent.com/assets/1009457/14002454/3e26b238-f1a0-11e5-9e20-23f0854d5ed0.png)

**Comment by ujuc** [comment]
@riseshia  이거랑 #109 번이랑 연결해서 하면 될것같은데요 어디까지 된거죠..?

**Comment by riseshia** [comment]
@ujuc 관계 없겠지만...!
타임존 받는 UI + 처리 해주면 끝납니다.
뷰단에서는 사용자가 접속한 브라우저 타임존 기준으로 보여주도록 전부 수정되어있어요.
