### ISSUE TITLE
mobile viewport가 빠졌어요!

### ISSUE THREAD

**Issue by say8425** [riseshia/cal4w#63]
저번에 모바일에서 접속했는데,
모바일 사이즈를 보여주지 못해서 확인해보니 [viewport가 빠져있더라요](http://getbootstrap.com/css/#overview-mobile) 

![img_4776](https://cloud.githubusercontent.com/assets/3258867/14041120/530badd6-f2b1-11e5-96fa-0f200206c2c2.PNG)

**Comment by ujuc** [comment]
아하! 그래서 안됐구나!

**Comment by say8425** [comment]
@riseshia 일하세요 왕자님! ㅋㅋㅋㅋ

**Comment by say8425** [comment]
으음,, viewport가 적용이 안됬습니다,,
왜 그런지 모르겠네요

**Comment by ujuc** [comment]
음? 잘못 박은거 아니에요.ㅡ.ㅡ? 페이지 소스 확인해보면 되죠..

**Comment by riseshia** [comment]
배포를 안해서...

**Comment by ujuc** [comment]
ㅡ.ㅡ.. 머지만했어...

**Comment by riseshia** [comment]
방금 배포했습니다.

**Comment by say8425** [comment]
오키 잘 작동합니다 ㅋㅋㅋㅋ
이슈 닫겠습니다
