### ISSUE TITLE
slack id에서 특문 validation이 허용 안됨

### ISSUE THREAD

**Issue by say8425** [riseshia/cal4w#65]
![2016-03-28 10 13 03](https://cloud.githubusercontent.com/assets/3258867/14068986/ada26942-f4cd-11e5-9d07-e5ccd9e70e24.png)

정규식을 `^@([A-Za-z0-9_]{1,15})$`이렇게 단순하게 짰는데
슬랙에서 ID에 특문을 허용한다는 것을 잊고 있었네요ㅠ

**Comment by riseshia** [comment]
`.`만 추가로 허용했습니다 'ㅂ'

**Comment by say8425** [comment]
slack 문서에서는 validation에 대한 거 못찾았는데
[다른 팀도 특문은 `.`만 추가](https://github.com/18F/dolores-landingham-bot/commit/823871cd04e72db5d76aa7f1dfa78a067146aa9d)했더군요. 이슈 닫아도 될거 같아요 ㅋㅋㅋ

빠른 배포 고마워요👍

**Comment by riseshia** [comment]
넵. 필요하면 그때 더 추가하던가 룰을 간단하게 만들어도 될거 같아요 :+1:
