### ISSUE TITLE
지도표시안됨

### ISSUE THREAD

**Issue by ujuc** [riseshia/cal4w#79]
![2016-04-15 16 11 28](https://cloud.githubusercontent.com/assets/624975/14553979/e3df6b62-0324-11e6-8853-39fef8064ad0.png)

여러개가 나와서 그런것일 수 도 잇을듯..한데 음...

**Comment by ujuc** [comment]
https://cal4w.nyatorie.com/events/85

**Comment by riseshia** [comment]
검색 결과 반영이 늦어서 그렇습니다. 페이지 띄우고 지도 검색 -> 결과 랜더링이라서.
제가 확인해보기로는 검색 결과가 많아서 그런게 맞네요 'ㅂ'

**Comment by riseshia** [comment]
고로 닫습니다 'ㅂ'

**Comment by ujuc** [comment]
네에
